spring.application.name=MindTrack-Back

spring.datasource.url=jdbc:postgresql://localhost:5432/mindtrackDB
spring.datasource.username= postgres
spring.datasource.password= admin1234

spring.jpa.show-sql=false
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=none