spring.application.name=MindTrack-Back

spring.jpa.show-sql=false
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://localhost:5432/mindtrackDB
spring.datasource.username= postgres
spring.datasource.password= admin1234

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

